apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: passwd
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: google
  target:
    name: passwd
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: my-passwd



