apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts
  timeout: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
  labels:
    app: reloader
spec:
  targetNamespace: reloader
  install:
    createNamespace: true
  releaseName: reloader #my-name
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: '1.0.58'
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
      interval: 1m
