---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chart
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/popilmv/cluster.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chart
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: chart
